### ISSUE TITLE
WDA is failing because of error: No Accounts: Add a new account in Accounts settings. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')

### ISSUE THREAD

**Issue by Jitu1888** [dryark/stf_ios_support#125]
1. I m running make command.
2. Getting the below error :
/Users/jenkins-lab4/iOS_UI/stf_ios_support/repos/WebDriverAgent/WebDriverAgent.xcodeproj: error: No Accounts: Add a new account in Accounts settings. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
/Users/jenkins-lab4/iOS_UI/stf_ios_support/repos/WebDriverAgent/WebDriverAgent.xcodeproj: error: No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
/Users/jenkins-lab4/iOS_UI/stf_ios_support/repos/WebDriverAgent/WebDriverAgent.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
/Users/jenkins-lab4/iOS_UI/stf_ios_support/repos/WebDriverAgent/WebDriverAgent.xcodeproj: error: No Accounts: Add a new account in Accounts settings. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
/Users/jenkins-lab4/iOS_UI/stf_ios_support/repos/WebDriverAgent/WebDriverAgent.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "Q4MQJVPJ5C" with a private key was found. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')

**Comment by Jitu1888** [comment]
bin/wda/build_info.json i dont have the build_info.json file. What does it contain @nanoscopic @mbilbiesi

**Comment by Jitu1888** [comment]
**bin/wda/build_info.json**: repos/WebDriverAgent repos/WebDriverAgent/WebDriverAgent.xcodeproj | repos/WebDriverAgent repos/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer/Info.plist
	@if [ -e bin/wda ]; then rm -rf bin/wda; fi;
	@mkdir -p bin/wda/Debug-iphoneos
	ln -s ../../repos/wdaproxy/web bin/wda/web
	$(eval XCODEOPS=$(shell jq '.xcode_build_ops // ""' config.json -j))
	cd repos/WebDriverAgent && xcodebuild $(xcodebuildoptions1) $(XCODEOPS) $(xcodebuildoptions2) build-for-testing
	$(eval PROD_PATH=$(shell ./get-wda-build-path.sh))
	@if [ "$(PROD_PATH)" != "" ]; then cp -r $(PROD_PATH)/ bin/wda/; fi;
	@if [ "$(PROD_PATH)" != "" ]; then ./get-version-info.sh --repo wda > bin/wda/build_info.json; fi;
	@if [ "$(PROD_PATH)" == "" ]; then echo FAIL TO GET PRODUCTION PATH - you should rerun make; exit 1; fi;

**Comment by Jitu1888** [comment]
Done. I m able to fix it

**Comment by Jitu1888** [comment]
its not an issue

**Comment by rajeshj93** [comment]
@Jitu1888 i"m also facing same issue and struck here, can you please help me out ?

**Comment by Jitu1888** [comment]
<img width="753" alt="image" src="https://github.com/dryark/stf_ios_support/assets/8565346/e6c98c51-904a-422c-abde-823fdfbae69a">
